<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~P</string>
	<key>name</key>
	<string>Processing.js</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(?i:application/processing)\b(.*?)(&gt;)</string>
			<key>end</key>
			<string>(&lt;/(script|SCRIPT))(&gt;)</string>
			<key>name</key>
			<string>meta.processing.js</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.js</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.js</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.js</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.function.js</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.end.js</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>match void function like: void myFunc(arg) { … }</string>
					<key>match</key>
					<string>\b(void)\s+([a-zA-Z_$]\w*)?\s*(\()(.*?)(\))</string>
					<key>name</key>
					<string>meta.function.processing.js</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.processing</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)(&lt;)(canvas).*?\s(width|height)="([\d]+(?:px)?)".*?\s(width|height)="([\d]+(?:px)?)"(?=[^&gt;]*&gt;&lt;/\2&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.html</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.function.processing</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>support.function.processing</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&gt;(&lt;)/)(\2)(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.scope.between-tag-pair.html</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.html</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.any.html</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.processing.js</string>
	<key>uuid</key>
	<string>254BBEC9-8107-421D-9848-F14F74E1B9C0</string>
</dict>
</plist>
